name: S3 Deployment

on:
  workflow_call:
    inputs:
      source_dir:
        description: 'Source directory to deploy'
        required: true
        type: string
      dest_dir:
        description: 'Target directory to deploy'
        required: true
        type: string
      delete_flag:
        description: 'Whether to delete files in the bucket that are not in the source'
        required: false
        default: true
        type: boolean
    secrets:
      S3_BUCKET_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 🔍 Debug AWS env values
      run: |
        echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}"
        echo "AWS_SECRET_ACCESS_KEY: (length ${#AWS_SECRET_ACCESS_KEY})"
        echo "AWS_REGION: ${AWS_REGION}"
        echo "S3_BUCKET_NAME: ${AWS_S3_BUCKET}"
        echo "DEST_DIR: ${DEST_DIR}"
        echo "SOURCE_DIR: ${SOURCE_DIR}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        SOURCE_DIR: ${{ inputs.source_dir }}
        DEST_DIR: ${{ inputs.dest_dir }}

    - name: Install AWS CLI (v2)
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Sync files to S3 (native AWS CLI)
      run: |
        echo "Syncing $SOURCE_DIR to s3://$AWS_S3_BUCKET/$DEST_DIR"
        aws s3 sync "$SOURCE_DIR" "s3://$AWS_S3_BUCKET/$DEST_DIR" $ARGS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        SOURCE_DIR: ${{ inputs.source_dir }}
        DEST_DIR: ${{ inputs.dest_dir }}
        ARGS: ${{ inputs.delete_flag == true && '--delete' || '' }}

